Console.WriteLine("Введите данные для Прямоугольника 1(x,y,w,h)");
double x1 = Convert.ToDouble(Console.ReadLine());
double y1 = Convert.ToDouble(Console.ReadLine());
double w1 = Convert.ToDouble(Console.ReadLine());
double h1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Введите данные для Прямоугольника 2(x,y,w,h)");
double x2 = Convert.ToDouble(Console.ReadLine());
double y2 = Convert.ToDouble(Console.ReadLine());
double w2 = Convert.ToDouble(Console.ReadLine());
double h2 = Convert.ToDouble(Console.ReadLine());
double x1_max = x1 + w1;
double y1_max = y1 + h1;
double x2_max = x2 + w2;
double y2_max = y2 + h2;
Console.WriteLine($"Прямоугольник 1: X от {x1} до {x1_max}, Y от {y1} до {y1_max}");
Console.WriteLine($"Прямоугольник 2: X от {x2} до {x2_max}, Y от {y2} до {y2_max}");
bool a_result = (x1 >= x2 && x1_max <= x2_max && y1 >= y2 && y1_max <= y2_max);
Console.WriteLine($"а) Первый полностью внутри второго: **{a_result}**");
bool b_result = a_result || (x2 >= x1 && x2_max <= x1_max && y2 >= y1 && y2_max <= y1_max);
Console.WriteLine($"б) Один полностью внутри другого: **{b_result}**");
bool intersect_result = !(x1_max <= x2 || x1 >= x2_max || y1_max <= y2 || y1 >= y2_max);
Console.WriteLine($"в)* Прямоугольники пересекаются: **{intersect_result}**");